version: '3.1'

services:
  springboot:
    build: .
    restart: always
    container_name: euclidean
    ports:
      - 8080:8080
    working_dir: /application
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always